### ISSUE TITLE
KeyError: 'n_prediction' while loading fine-tuned model

### ISSUE THREAD

**Issue by devsteppe9** [tanreinama/text2text-japanese#3]
Hello Sir! @tanreinama 

Thank you for the project providing us! 
I tried to use your news2title model for summarizing Japanese text. But I encountered error below. If you know the reason please let me know. Thank you in advance!

**Command:**

`python text2text.py --model news2title-medium --context "text2text-japaneseとは、gpt2-japaneseのモデルを、文章→文章の変換タスク用にファインチューニングするためのプログラムです。gpt2-japaneseのプレトレーニング済みモデルは教師なし学習による言語モデルですが、それを元に、教師あり学習による文章変換モデルを作成します。質問回答AI、チャットボット、抽象型要約などに使えます。"`

``
**Error:**

> Traceback (most recent call last):
>   File "text2text.py", line 41, in <module>
>     max_length = params['n_prediction']
> KeyError: 'n_prediction'

**Comment by tanreinama** [comment]
Please check out the contents of news2title-medium/hparams.json.
The correct content is as follows.

```
{"n_vocab": 20573, "n_ctx": 1024, "n_embd": 1024, "n_head": 16, "n_layer": 24, "n_prediction": 160}
```

If the content is incorrect or hparams.json does not exist, please download and unarchive the model again.

**Comment by devsteppe9** [comment]
Thank you for the response!
Fixed by adding `n_prediction`  keyword into `model.py` file.  I created pull request here #4
