### ISSUE TITLE
サンプル文を学習させようとしてもIndexErrorが発生して落ちる

### ISSUE THREAD

**Issue by embeddedsamurai** [tanreinama/text2text-japanese#5]
@tanreinama 

READMEにかいてある

今日の昼飯は<|SEP|>焼肉定食

を 00.txtとしてひとつだけ作成し，train_dataディレクトリ以下に格納し　以下実行すると

python3 make_data.py --src_dir train_data --dst_file pairtext
python3 training.py --max_train_steps 10 --base_model gpt2ja-medium --run_name run1 --dataset "pairtext_*.pkl"

以下のエラーが発生し，落ちてしまいます。

Loading checkpoint gpt2ja-medium/model-10410000
Loading dataset...
There is 0 chunks.
Training...
Traceback (most recent call last):
  File "training.py", line 327, in <module>
    main()
  File "training.py", line 300, in main
    feed_dict=sample_feature())
  File "training.py", line 222, in sample_feature
    idx = global_chunk_index[global_chunk_step]
IndexError: index 0 is out of bounds for axis 0 with size 0

サンプル例が落ちてしまう現象が起きているので報告です。
原因は，調べていません。

**Comment by tanreinama** [comment]
READMEに書いてある手順にオプション指定が抜けていました。
make_data.pyに、「--split_tag "<|SEP|>"」とテキストを分けるタグを指定することで、動くようになります。
